# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../Algorithms/BilateralMeshDenoising.h \
    ../Algorithms/BilateralNormalFilteringForMeshDenoising.h \
    ../Algorithms/ProjectivePropagationMeshFiltering.h \
    ../Algorithms/seg_sort.h \
    ../DenoisingFacade.h \
    ../Algorithms/FastAndEffectiveFeaturePreservingMeshDenoising.h \
    ../Algorithms/GuidedMeshNormalFiltering.h \
    ../Algorithms/MeshDenoisingBase.h \
    ../Algorithms/MeshDenoisingViaL0Minimization.h \
    ../Algorithms/NonIterativeFeaturePreservingMeshFiltering.h \
    ../Algorithms/PropagationMeshFiltering.h \
    ../Algorithms/ShortestPropagationMeshFiltering.h \
    ../datamanager.h \
    ../Algorithms/dijkstra.h \
    ../mesh.h \
    ../Algorithms/noise.h \
    ../parameterset.h
SOURCES += ../Algorithms/BilateralMeshDenoising.cpp \
    ../Algorithms/BilateralNormalFilteringForMeshDenoising.cpp \
    ../Algorithms/ProjectivePropagationMeshFiltering.cpp \
    ../Algorithms/seg_sort.cpp \
    ../DenoisingFacade.cpp \
    ../Algorithms/FastAndEffectiveFeaturePreservingMeshDenoising.cpp \
    ../Algorithms/GuidedMeshNormalFiltering.cpp \
    ../Algorithms/MeshDenoisingBase.cpp \
    ../Algorithms/MeshDenoisingViaL0Minimization.cpp \
    ../Algorithms/NonIterativeFeaturePreservingMeshFiltering.cpp \
    ../Algorithms/PropagationMeshFiltering.cpp \
    ../Algorithms/ShortestPropagationMeshFiltering.cpp \
    ../datamanager.cpp \
    ../Algorithms/dijkstra.cpp \
    ./main.cpp \
    ../Algorithms/noise.cpp \
    ../parameterset.cpp
