% ---------------------------------------------------------------------
% EG author guidelines plus sample file for EG publication using LaTeX2e input
% D.Fellner, v1.17, Sep 23, 2010


\title[Mesh denoising via generalized intrinsic filter on 2D manifold]%
    {Mesh denoising via generalized intrinsic filter on 2d manifold}
    %{Mesh denoising via intrinsic normal filter}

% for anonymous conference submission please enter your SUBMISSION ID
% instead of the author's name (and leave the affiliation blank) !!

%\author[B. Liu \& J. J. Cao \&N. Ma \& W. M. Wang \& L. G. Liu \& X. P. Liu]
       %{B. Liu$^{1}$  W. M. Wang$^{1}$  J. J. Cao$^{1}$  N. Ma$^{1}$  L. G. Liu$^{2}$ and
        %X. P. Liu\thanks{xpliu@dlut.edu.cn}$^{1}$\\
         %$^1$Dalian University of Technology, China\\
         %$^2$University of Science and Technology of China, China
       %}

% ------------------------------------------------------------------------

% if the Editors-in-Chief have given you the data, you may uncomment
% the following five lines and insert it here
%
% \volume{27}   % the volume in which the issue will be published;
% \issue{1}     % the issue number of the publication
% \pStartPage{1}      % set starting page


%-------------------------------------------------------------------------
\begin{document}


\maketitle



\input{abstract}
\input{introduction}
\input{related}
\input{algorithm}
\input{results}
%\input{supp}

%-------------------------------------------------------------------------

%\bibliographystyle{eg-alpha}
\bibliographystyle{eg-alpha-doi}

\bibliography{EGauthorGuidelines-conf-sub}

%-------------------------------------------------------------------------

\end{document}
